### PR TITLE
Staticize facade and complete API actions

### PR DESCRIPTION
**Pull request by alexstewartja**
These changes conform this package to follow the "Laravel Way".

## Changes

- The API actions wrapped by the Coinbase facade are now truly staticized.

- Invoice management functionality has been implemented and missing actions for Charges (cancel and resolve) have also been implemented.

- Readme has been updated commensurately with changes made to the codebase. 

## Checklist

- [x] Docs are complying/updated
- [x] Tests are passing

### CODE REVIEW

**Comment by alexstewartja** [comment]
@antimech @pierre-pizzetta , any word from @shakurov ? He seemed to have taken an extended vacation from this package.

**Comment by antimech** [comment]
@alexstewartja no answers from him. I'll take a look at your PR.

**Comment by antimech** [comment]
LGTM but the merge conflict must be fixed and it seems like you haven't ticked the "allow edits from maintainers",

**Comment by alexstewartja** [comment]
"Allow edits" enabled

**Comment by alexstewartja** [comment]
🚀

**Comment by antimech** [comment]
I don't have access to the repository settings and can't enable packagist auto-update. Your changes are available in [antimech/coinbase](https://packagist.org/packages/antimech/coinbase). I recommend switching to my repository from now on:
```shell
composer remove shakurov/coinbase
composer require antimech/coinbase
```

**Comment by alexstewartja** [comment]
Seems to have been (manually) updating quite fine until today: https://packagist.org/packages/shakurov/coinbase

What went wrong?

**Comment by antimech** [comment]
Manual updates are under big delay. Plus I have to wait until I can request it.

**Comment by antimech** [comment]
I've updated it, manual updates available once in 24 hours. I'll support this package for some time for graceful replacement.

**Pull request merged**
